### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by fulldecent** [ChiefPilot/F3BarGauge#3]
This project is great, and mature.

Please add to CocoaPods.

**Comment by fulldecent** [comment]
Note: I have forked and rewritten in Swift at https://github.com/fulldecent/FDBarGuage/blob/master/README.md

**Comment by ChiefPilot** [comment]
Heya,

Sorry for the delay in getting back to you - I've been off grid all 
week.

This looks awesome - nice job!   I've thought about going back and 
redoing this control a couple of times; as you may have noticed, there 
are some inefficiencies in how it's drawn and since I first put it out 
there Swift has happened and Cocoapods have become a widely accepted 
thing.

Thanks for the note and again great job - the swift implementation 
looks great!

-Brad

**Comment by fulldecent** [comment]
Closing, it seems like little interest to get into CocoaPods.
